name: Android CI - Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android packages
      run: |
        sdkmanager --licenses >/dev/null || true
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build Release APK
      env:
        GRADLE_USER_HOME: .gradle
      run: ./gradlew clean :app:assembleRelease --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: GeoTools-GeoSul-APK-Release
        path: app/build/outputs/apk/release/*.apk

    - name: Upload Debug APK (fallback)
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: GeoTools-GeoSul-APK-Debug
        path: app/build/outputs/apk/debug/*.apk
